### PR TITLE
Deformed mesh

### PR DESCRIPTION
**Pull request by jmansour**
heya julz!  thought i'd test this pull request workflow, so i've nominated yourself to do a bit of review on the work in here. 

basically, i've added a 'context manager' to allow users to deform the mesh.  in python, context managers are invoked using the 'with' keyword.  basically, they force users to do certain operations within a block (indent as per the usual python style).. most importantly, the context manager runs certain operations at the beginning, and at the end of the block.   in this case, at the beginning of the block, the mesh data is set to be writeable, and at the end of the block it is set back to read-only, but also any submesh are updated automatically. 

there's also a few other unrelated changes in this branch (fixing error messages etc).  in the future i'll try and keep all changes within a branch to be pretty focussed on the branch task, and switch back to main branch (using 'git shelve' etc) for other minor updates.

### CODE REVIEW

**Comment by julesghub** [comment]
yo, i had a look though. Looks good!
is the 'with' able to be a pattern for writing to uw objects in general?

Note: I haven't followed every bit of the whole change branch because
looking through multiple git changesets is time consuming.

How about we discuss more on quality day? this wednesday right?

**Comment by jmansour** [comment]
Where appropriate, I don't see why not (re: using 'with' statement). 

Yes, the review process can be time consuming. I guess it's a question of whether it's necessary and whether we want to adopt it.  A good topic for 'quality day'!

**Comment by jmansour** [comment]
discovered there are efficiency issues here.  switching to the non-regular routines comes at a huge cost (particle advection takes ~20 times longer).  

normally we use FeMesh_ElementType_ElementHasPoint_ForIrregular, which isn't invoked in the implementation on this branch.  however, this method is broken for q2 elements.  

i think we should merge changes in none the less, and start a new issue on the issue tracker so I can come back to this shortly.

**Comment by lmoresi** [comment]
Julian and I had conversations about this question for structured v. Unstructured representations of the spherical mesh. There are efficient ways to navigate unstructured grids which we need to have at our disposal

Sent from my iPhone

On 5 Oct 2015, at 02:35, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


discovered there are efficiency issues here. switching to the non-regular routines comes at a huge cost (particle advection takes ~20 times longer).

normally we use FeMesh_ElementType_ElementHasPoint_ForIrregular, which isn't invoked in the implementation on this branch. however, this method is broken for q2 elements.

i think we should merge changes in none the less, and start a new issue on the issue tracker so I can come back to this shortly.

**Pull request merged**
