### PR TITLE
V27

### PR DESCRIPTION
**Pull request by arijitlaik**
My  Issue #335  seems to be resolved by this suggestion from John. keep it here for reference

### CODE REVIEW

**Comment by jmansour** [comment]
Thanks for finding this @arijitlaik!

**Comment by tingyang2004** [comment]
So the only thing you need to do is to switch
    Mesh_GetLocalCoordRange( mesh, minCrd, maxCrd );
to
    Mesh_GetDomainCoordRange( mesh, minCrd, maxCrd );
in libUnderworld/StgDomain/Swarm/src/ElementCellLayout.c?

Anything else others should know about this issue? @arijitlaik @jmansour

**Comment by tingyang2004** [comment]
Thanks, very helpful thing. @jmansour

**Comment by arijitlaik** [comment]
@jmansour welcome and thanks, @tingyang2004 the last i checked there were no further issues, I hope your models aren't experiencing any issues.
Sorry for the late reply I am on a leave from work.

**Comment by tingyang2004** [comment]
Thanks for asking, so far so good.

**Pull request merged**
