### PR TITLE
Surface integration

### PR DESCRIPTION
**Pull request by jmansour**
New surface jacobian algorithm.  It uses the full Jacobian to extract the portion for the required surface, and is more simple & general in usage.  I believe this should make most of the surface Jacobian code (each element type has its own) redundant.

I will leave the existing code for now, but it should probably be culled if it's truly no longer necessary.  Note that my algo will probably be slightly slower (the full Jacobian is calculated), but it'll be negligible.

### CODE REVIEW

**Comment by julesghub** [comment]
@jmansour - nice stuff, the example notebook is very cool.

Things to improve..
- Add error check in function _ElementType_SurfaceNormal() - Journal_Firewall if none of the function conditions are meet
- Some of the indentation in the c coding is a mixed bag. The old code uses tabs, you use spaces. Just make it consistent for the file, eg ElementType.c. In future we could go astyle/clang mad and justify all c/c++
- Change the 'integrate()' to 'evaluate()' for the Integral python class. It would be more consistent with other python objects if the function name were to be "evaluate()"
- Add some doc strings to the ipynb example around the checking functions, ie 
def checkSurfaceIntegration(mesh, value, rtol=1e-05)
- Add a test in the ipynb that integrates a function other than fn=1.0 - more robust testing on the input

done!

**Comment by jmansour** [comment]
Ok, all done!  
I've gone ahead and culled the old surface jacobian functionality. 
I've also updated the existing unit tests (within testStgFEM) to use the new surface jacobian function.  They are also passing (the ElementType tests are that is).

**Comment by julesghub** [comment]
@jmansour  RT model down..... so are some other tuts 
(Total: Number of fails 3
['../docs/tutorials/1_03_BlankenbachBenchmark.ipynb', '../docs/tutorials/1_05_StokesSinker.ipynb', '../docs/tutorials/1_06_Rayleigh_Taylor.ipynb'])

I think you changed the Interface.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-600fd5cf129c> in <module>()
      1 vdotv = fn.math.dot( velocityField, velocityField )
----> 2 v2sum_integral  = uw.utils.Integral( feMesh=velocityMesh, fn=vdotv )
      3 volume_integral = uw.utils.Integral( feMesh=velocityMesh, fn=1. )

/home/jgiordani/codes/underworld2_clean_git/underworld/_stgermain.pyc in __call__(cls, *args, **kwargs)
     89         # create the instance as normal.  this will invoke the class's
     90         # __init__'s as expected.
---> 91         self = super(_SetupClass, cls).__call__(*args, **kwargs)
     92 
     93         # this steps through the MRO in ascending order (so that child

**Comment by jmansour** [comment]
fixed now

**Pull request merged**
