### PR TITLE
Stat

### PR DESCRIPTION
**Pull request by jmansour**
Hey @rbeucher  & @julesghub 

I haven't run all tests, but i'll wait for Jenkins to report back a yea or nay. 

Also, I still need to do a small write-up for the 2.9 blog post. 

Check changeset messages for details. 

I'm gonna tests this on raijin shortly.

### CODE REVIEW

**Comment by julesghub** [comment]
Error from the latest jenkins run - http://130.56.252.251:32779/job/Underworld2/job/PR-419/2/execution/node/3/ws/testResults/test_29__func_debug_messages.py.err/*view*/

**Comment by jmansour** [comment]
thanks. was gonna ask for that, as couldn't find it in the browser and couldn't reproduce local. 

fix incoming.

**Comment by julesghub** [comment]
exampleOfJenkins

How you can use jenkins to browse the testResults. 
Note this looks into the "workspace" of jenkins slave machine, which is a temporary space, it only holds the previous 2 builds from memory.

**Comment by jmansour** [comment]
Yeah would never have found that! Thanks for vid.

**Comment by rbeucher** [comment]
Is this good to go @jmansour ?

**Comment by julesghub** [comment]
I ran a few jobs with it on raijin ~16procs. It seemed stable.

**Comment by jmansour** [comment]
@julesghub that model part of the testing procedure. It is executed by `function_debug_messages.py`

@rbeucher I just want to write a blog post entry for it, then i'll merge it in.

**Comment by jmansour** [comment]
Actually, I'll rebase/merge but leave this PR open until I add the blog entry.

**Comment by jmansour** [comment]
Ok, seems merging also closes  the PR.  I guess I'll get the blog entry done today.

**Pull request merged**
