### PR TITLE
adding fssa to the release

### PR DESCRIPTION
**Pull request by julesghub**
This is a work in progress and is been added it to the release unfinished.

Please don't expect this to work out of the box ;)

### CODE REVIEW

**Comment by julesghub** [comment]
@rbeucher - are the changes to the Dockerfiles in this pull request ok for the recent work you've done?
If so please squash and merge into 2.12, otherwise let me know. Thanks

**Comment by rbeucher** [comment]
No it does not work. I'll have a look tomorrow

**Comment by julesghub** [comment]
The dockerfile stuff? Or other things?

**Comment by rbeucher** [comment]
The docker stuff

**Pull request merged**
