### PR TITLE
Update CI.yml

### PR DESCRIPTION
**Pull request by julesghub**
Use scripts to build dockers `linux/arm64` and `linux/amd64`.
Removing manifest commands as that seems to be automated now.

### CODE REVIEW

**Comment by julesghub** [comment]
Don't merge yet, until we a satisfied the new dockers on dockerhub are correct.

**Comment by rbeucher** [comment]
What do you mean? the manifest is automated now?

**Comment by julesghub** [comment]
Specifying multiple platforms in the docker-build-push action seems to do the job of the docker manifest commands that were previously there.
I tested by building & pushing a test dockers image, (with multiple platforms: one arm the or amd), to docker hub and it all seemed to work correctly. See https://hub.docker.com/repository/docker/julesg/test_docker_builds

**Comment by rbeucher** [comment]
OK something must have changed because it was not working very well last time I tried...

**Pull request closed without merging**
