### PR TITLE
Release fixes

### PR DESCRIPTION
**Pull request by jmansour**
Check commit message.
Image test still broken.

### CODE REVIEW

**Comment by jmansour** [comment]
Argh.. this includes NN/kdtree history.  Ignore that.

**Comment by jmansour** [comment]
I actually think it's a change going to PETSc 3.11.  A few of the iteration counts have increase by 1. 

Note that I actually loosened the iteration count requirements for the other `solver_*.py` tests, and this one still had some of the old implementation that I hadn't noticed (check for exact counts). 

Should we confirm 100% that it's a difference due to petsc versions?

**Comment by jmansour** [comment]
PETSc 3.7
```bash
Pressure iterations:   5
Velocity iterations:   9 (presolve)      
Velocity iterations:  35 (pressure solve)
Velocity iterations:   7 (backsolve)     
Velocity iterations:  51 (total solve)   
```

PETSc 3.11
```bash
Pressure iterations:   5
Velocity iterations:  10 (presolve)      
Velocity iterations:  36 (pressure solve)
Velocity iterations:   8 (backsolve)     
Velocity iterations:  54 (total solve)   
```
Not a dramatic difference, but would be good to know the cause.

**Comment by julesghub** [comment]
@jmansour is the inclusion of the NN stuff in this PR a problem? I want to merge the fixes into the stuff i'm doing with SLADE....unrelated developments, just being thorough.

**Comment by jmansour** [comment]
No I don't think it should be a problem. It's merged into dev now, so won't
be merged in twice.

**Pull request merged**
