### PR TITLE
Conda

### PR DESCRIPTION
**Pull request by rbeucher**
Here are the changes I made to make the conda build.
We will need to update the recipe to build from the release tarball once we have a release

### CODE REVIEW

**Comment by jmansour** [comment]
So what's the process at release time for conda? 

We should update `release_guidelines.md` accordingly so we don't forget.

**Comment by rbeucher** [comment]
OK so we will have to update the "url" and "sha256" tags.
Ideally we want them to point at the release tarball so that needs to be done after the release is done.
That's the guideline for conda-forge. 
We discussed with @lmoresi  and for now we only want to push stuff to our underworldcode channel so pointing at master is probably fine.

**Comment by jmansour** [comment]
Can you add comments to the `release_guidelines.md` to that effect? 

So just for info here, I can report success with:
Debian 9 (via wsl)
Ubuntu 20.04 (via wsl). 

Was @lmoresi successful on OSX?  I've got a mac around here I can give it a go on.

**Comment by rbeucher** [comment]
Yes successful on OSX. Let me push the changes

**Comment by rbeucher** [comment]
Good to go I think

**Comment by jmansour** [comment]
Put something in `CHANGES.md` too.

**Review by julesghub — CHANGES_REQUESTED** [review]
Looks all good to me and worked on my Ubuntu 20.04.

I agree with @jmansour about the CHANGES.md update. Please add a line.... and then blog post blog post plog bost!

**Comment by jmansour** [comment]
Blog post !!! Blog post !!! Blog post !!!

**Comment by rbeucher** [comment]
@julesghub should be good to go. Please merge when you can.

**Review by julesghub — APPROVED** [review]

**Pull request merged**
