### PR TITLE
Pip install first cut

### PR DESCRIPTION
**Pull request by jmansour**
Please try!  

```bash
pip install -v  git+https://github.com/jmansour/underworld2@pip
```

Note that this pull request includes changesets from the KDTree pull request, which haven't been merged in yet.

### CODE REVIEW

**Comment by julesghub** [comment]
I tried it with the base docker image here https://hub.docker.com/r/underworldcode/petsc4py
It worked! But I modified the pip command to use --user, ie.
`pip install --user -v git+https://github.com/jmansour/underworld2@pip`

Unfortunately glucifer isn't available as a python module, so none of the repo's example files work. Thoughts @jmansour?

Otherwise it installs cleanly. Nice!

**Comment by jmansour** [comment]
Yes, I've had to reorganise things somewhat.  Check the e836925 changeset message.   Basically, i've moved `glucifer` and `libUnderworld` into `underworld`.  There isn't really any reason for them to live independently, and it causes difficulty for pip.  So for `glucifer`, we'll need to update the models to do this:
```python
from underworld.glucifer import glucifer
```
I suggest we start a new release branch soon, and keep PR out until the following release.

**Comment by julesghub** [comment]
I like the idea of glucifer under underworld makes sense from the numerics and marketing side.
I agree with leaving the PR out until after the next release.

This sed command should help updating the ipynbs... script'o'doom style.
`sed -i 's/import\s\+glucifer/from underworld.glucifier import glucifer'/g *.ipynb`

**Comment by lmoresi** [comment]
Oh yes … scripts of doom !

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 13 Jun 2019, 2:57 AM +0100, Julian Giordani <notifications@github.com>, wrote:

I like the idea of glucifer under underworld makes sense from the numerics and marketing side.
I agree with leaving the PR out until after the next release.

This sed command should help updating the ipynbs... script'o'doom style.
sed -i 's/import\s\+glucifer/from underworld.glucifier import glucifer'/g *.ipynb

**Comment by lmoresi** [comment]
Like others, I have only tried this on the docker/petsc4py image and also with --user as it was just for testing. My primary suggestion would be to try to cut down on the verbosity. I hate it when pip fails as it is usually very hard to figure out the errors and how to fix them, but perhaps with our installation we can try to suppress the chatter when it is not failing.

**Comment by jmansour** [comment]
Do you mean even when installing without the verbosity flag `-v` ¿

**Comment by OKaluza** [comment]
Installed it here in a python3.6.6 virtualenv, ubuntu 18.04, everything goes fine up to importing the module:
```
>>> import underworld
--------------------------------------------------------------------------
Open MPI has detected that this process has attempted to initialize
MPI (via MPI_INIT or MPI_INIT_THREAD) more than once.  This is
erroneous.
--------------------------------------------------------------------------
[ok-M3800:31433] *** An error occurred in MPI_Init
[ok-M3800:31433] *** reported by process [3597402113,0]
[ok-M3800:31433] *** on a NULL communicator
[ok-M3800:31433] *** Unknown error
[ok-M3800:31433] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[ok-M3800:31433] ***    and potentially your MPI job)
```

**Comment by jmansour** [comment]
Thanks Owen! Interesting.

Is it possibly linked against a different mpi to mpi4py?

**Comment by OKaluza** [comment]
> Thanks Owen! Interesting. Is it possibly linked against a different mpi to mpi4py?

Doesn't seem to be...
```
(python3-default) owen@ok-M3800:~/Dropbox/LavaVu$ ldd /home/owen/python3-default/lib/python3.6/site-packages/underworld/lib/libUnderworld.so 
        linux-vdso.so.1 (0x00007ffff4f2f000)
        libPICellerator.so => /home/owen/python3-default/lib/python3.6/site-packages/underworld/lib/libPICellerator.so (0x00007f807d60d000)
        libStgFEM.so => /home/owen/python3-default/lib/python3.6/site-packages/underworld/lib/libStgFEM.so (0x00007f807d3b1000)
        libStgDomain.so => /home/owen/python3-default/lib/python3.6/site-packages/underworld/lib/libStgDomain.so (0x00007f807d146000)
        libStGermain.so => /home/owen/python3-default/lib/python3.6/site-packages/underworld/lib/libStGermain.so (0x00007f807cec5000)
        libpetsc.so.3.11 => /home/owen/python3-default/lib/python3.6/site-packages/petsc/lib/libpetsc.so.3.11 (0x00007f807bb5a000)
        libmpi_cxx.so.20 => /usr/lib/x86_64-linux-gnu/libmpi_cxx.so.20 (0x00007f807b940000)
        libmpi.so.20 => /usr/lib/x86_64-linux-gnu/libmpi.so.20 (0x00007f807b64e000)
...
                           
(python3-default) owen@ok-M3800:~/Dropbox/LavaVu$ ldd /home/owen/python3-default/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007ffde3bbf000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbbfecf4000)
        libmpi.so.20 => /usr/lib/x86_64-linux-gnu/libmpi.so.20 (0x00007fbbfea02000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbbfe611000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbbff27a000)
        libopen-rte.so.20 => /usr/lib/x86_64-linux-gnu/libopen-rte.so.20 (0x00007fbbfe389000)
        libopen-pal.so.20 => /usr/lib/x86_64-linux-gnu/libopen-pal.so.20 (0x00007fbbfe0d7000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbbfdecf000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbbfdb31000)
        libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007fbbfd8f4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbbfd6d5000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fbbfd4d2000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007fbbfd2c7000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007fbbfd0bd000)
```

**Comment by jmansour** [comment]
And there's no PYTHONPATH still hanging around pointing to other uw
installs?

**Comment by arijitlaik** [comment]
works with 18.04 and distro petsc and mpich :)

**Comment by OKaluza** [comment]
> And there's no PYTHONPATH still hanging around pointing to other uw installs?

Nothing in PYTHONPATH.
My MPI is not mpich, it's the default system OpenMPI package from mpi-default-bin, also have libhdf5-mpi-dev installed if that matters.

**Comment by jmansour** [comment]
@OKaluza that's identical to what i'm running here (via WSL).  Can you confirm that `petsc` is using MPI? 

```bash
ldd /home/owen/python3-default/lib/python3.6/site-packages/petsc/lib/libpetsc.so.3.11
```
It should be, unless you've installed it before you installed MPI, which I'm guessing you haven't.

**Comment by OKaluza** [comment]
Seems to be good, import petsc works fine on its own too:
```
ldd /home/owen/python3-default/lib/python3.6/site-packages/petsc/lib/libpetsc.so.3.11
        linux-vdso.so.1 (0x00007fff281b8000)
        liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f9c1b7bb000)
        libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f9c1b560000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9c1b1c2000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f9c1ae8a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9c1ac86000)
        libmpi_mpifh.so.20 => /usr/lib/x86_64-linux-gnu/libmpi_mpifh.so.20 (0x00007f9c1aa2f000)
        libmpi.so.20 => /usr/lib/x86_64-linux-gnu/libmpi.so.20 (0x00007f9c1a73d000)
...
```
I tried breaking on MPI_Init and MPI_Init_thread in gdb, 
First it hits Init_thread called from mpi4py:
```
Breakpoint 3, 0x00007ffff556b3c0 in PMPI_Init_thread () from /usr/lib/x86_64-linux-gnu/libmpi.so.20
(gdb) bt
#0  0x00007ffff556b3c0 in PMPI_Init_thread () from /usr/lib/x86_64-linux-gnu/libmpi.so.20
#1  0x00007ffff4306b01 in PyMPI_OPENMPI_MPI_Init_thread (provided=0x7fffffff8fa0, required=3, argv=0x0, argc=0x0)
    at src/lib-mpi/compat/openmpi.h:119
#2  __pyx_f_6mpi4py_3MPI_bootstrap () at src/mpi4py.MPI.c:7034
#3  PyInit_MPI () at src/mpi4py.MPI.c:32255
#4  0x00000000005eebc8 in _PyImport_LoadDynamicModuleWithSpec ()
```
Then it hits init called from Stg which seems to cause the aforementioned crash.
```
Thread 1 "python" hit Breakpoint 1, 0x00007ffff556b240 in PMPI_Init () from /usr/lib/x86_64-linux-gnu/libmpi.so.20
(gdb) bt
#0  0x00007ffff556b240 in PMPI_Init () from /usr/lib/x86_64-linux-gnu/libmpi.so.20
#1  0x00007fffb0c11f61 in StgInit (argc=<optimised out>, argc@entry=1, argv=<optimised out>, argv@entry=0x112c370)
    at libUnderworldPy/StGermain_Tools.c:34
#2  0x00007fffb0c14886 in _wrap_StgInit (args=0x7ffff7e70808) at libUnderworldPy/StGermain_Tools_wrap.cxx:4079
#3  0x000000000051187c in ?? ()
#4  0x00000000004f5277 in _PyEval_EvalFrameDefault ()
```

**Comment by jmansour** [comment]
Ok, I've managed to reproduce this.  My `h5py` install was non-MPI, but when I reinstalled with MPI h5py, I encounter the same issue.  Note that we currently always import h5py when we import underworld to ensure we don't get clashes with petsc's possible libhdf5 linking.

I made various changes around this and `MPI_Init()` `MPI_Finalize()` etc recently. It's all quite fragile unfortunately due to Python's garbage collection (which is somewhat unpredictable).

**Comment by OKaluza** [comment]
@jmansour yep, working now, I uninstalled libhdf5-mpi (which removes petsc-dev too, plus opencv packages) uninstalled h5py (custom built with CC=mpicc etc) and reinstalled default h5py, petsc then underworld with pip.

**Comment by jmansour** [comment]
Hey @julesghub .  I think this bad boy is ready to merge, but you'll be the final judge of that!   

I've even done a post:
https://medium.com/underworldcode/underworld-2-9-8521e55e4f57

**Comment by jmansour** [comment]
Also, @julesghub, note that i've modified `test_basic.sh` so that it no longer sets `PYTHONPATH`.  This may mess with your jenkins setups.

**Comment by julesghub** [comment]
@jmansour  Will get to it later today - will have to download and perhaps talk with you about it. 
In general I think squashing the commits together should be done at the PR acceptance not during the request.

**Comment by jmansour** [comment]
Yeah I can see that the history might be useful.   Keep in mind for next
time.

**Comment by julesghub** [comment]
@jmansour did you build the docker? it's failing for jenkins.

**Pull request merged**
