### PR TITLE
Docker updates

### PR DESCRIPTION
**Pull request by jmansour**
* Switch to ubuntu 20.04 base image
* Some rework of multistage builds
* Use repo osmesa as it now supports offscreen without xvfb.
* Switch to petsc 3.14
* Switch to mpich 3.3.2
* Switch to development version h5py
* Add jupyterlab

### CODE REVIEW

**Comment by jmansour** [comment]
@julesghub note that the images at dockerhub have been update with these recipes.

**Comment by julesghub** [comment]
Goodbye debian hello Ubuntu!

This is all for a "dev" docker right? If so, it looks good to me. I suppose for a release we select stable versions of things like h5py and remove valgrind and other bits?
If yes, then can you make a note of this in the release documents?

**Comment by jmansour** [comment]
So for `h5py`, it seems the PyPy version is a bit old and it isn't compatible with recent versions of `libHDF5` (in particular, the version that `petsc` pulls down).  That's why I've switched to the git version of `h5py`.  I think it's probably sufficiently stable for our stable release, but if the PyPy version works by then then that'd also be fine. 

`valgrind` etc I'm not too fussed either way, as they shouldn't be too big and they might still be useful for debugging.  But yes we should confirm that they aren't taking much space. 

The switch to Ubuntu was mainly because its repos are generally more up to date, and in particular its `osmesa` version allowed for offscreen rendering without `xvfb`, whereas we previously built `osmesa` from scratch to achieve this. 

Ah yes, good point on release notes..  we should have a checklist somewhere that git forces you to consider somehow.  I'll update the release notes now.

**Comment by julesghub** [comment]
Did you get anywhere on the release notes?

**Comment by jmansour** [comment]
It's in there.  Check the commits.

**Comment by julesghub** [comment]
I only see changes to the CHANGES.md, not release notes. 
Also in the changelog you should put the version numbers of dependencies. Best to be explicit I reckon.

**Comment by jmansour** [comment]
Versions added to `CHANGES.md`.  Which _release notes_ are you referring to JG?

**Comment by julesghub** [comment]
https://github.com/underworldcode/underworld2/blob/development/docs/development/release_guidelines.md

**Comment by jmansour** [comment]
These changes didn't really have any bearing on the the release guidelines, but they were a bit out of date in any case so I've updated. 

@rbeucher, I've removed the `petsc4py` images. Is that okay?  `docs/development/docker/petsc/Dockerfile` will generate a `petsc4py` environment.

**Review by julesghub — COMMENTED** [review]
Nice, looks all good with me!

**Review by julesghub — APPROVED** [review]

**Comment by jmansour** [comment]
Thanks team!

**Pull request merged**
