### PR TITLE
CMake new Building system

### PR DESCRIPTION
**Pull request by rbeucher**
# PR Checklist

- [X] I have read the `CONTRIBUTING.rst` document.
- [X] I have updated the docstrings accordingly.
- [X] I have updated `CHANGES.md`.
- [X] I have added tests which give complete coverage for my changes.
- [X] I have provided a usage example for my changes. 
- [X] All new and existing tests pass.

So this is the new CMake building system.
I have tested it on Linux and MacOSX Catalina.

I can generate conda builds for linux without issues.
I still have problems with the conda builds on the Mac.. Not sure what is going on.

### CODE REVIEW

**Comment by rbeucher** [comment]
It's been quite an effort. I don't understand what is going on with the MacOSX conda build. I must be missing something trivial.
I don't have a mac to test it further though....

**Comment by lmoresi** [comment]
I do have a mac but the M1 variety at the moment so there is no conda petsc ... I am not sure whether it would help if I did something ?

**Comment by jmansour** [comment]
Why were all the header changes required?  I assume `pip install` functionality still works?

**Comment by rbeucher** [comment]
I don't think it will work on the M1. Maybe using Rosetta? I would like to test more but I can't access the Mac at RSES....And I have used all my credit on the virtual Mac I hired.

**Comment by rbeucher** [comment]
> Why were all the header changes required? I assume `pip install` functionality still works?

Yes, that's how you install it.. `pip install`

I had to reorganize the code tree a bit. ;-) Lots of path were relative and it made things complicated. The installation directory should be movable now.

**Comment by rbeucher** [comment]
Scons add an extra step where it copied the source files to a new build directory...That complicated things a lot, I got rid of that step which required changing the tree structure a bit.

**Comment by rbeucher** [comment]
Note that conda builds on Linux and the Mac. It's just that on the Mac, it crashes when I import underworld...and that is just for conda. I tried a native build on Catalina and i's fine.

**Comment by jmansour** [comment]
I'll give it a go on my Mac shortly.

**Comment by rbeucher** [comment]
It also works fine in a python virtualenv. I just need to make CMake find Petsc if it was installed in the virtual environment. For now you need to make sure that PETSC_DIR is defined and points to the correct PETSc.

**Comment by rbeucher** [comment]
> I'll give it a go on my Mac shortly.

I tried using PETSc (3.15) installed via Brew. I just defined PETSC_DIR to point to PETSc and then ran "pip install -vv underworld"

**Comment by jmansour** [comment]
Okay, so I just built this on my Macbook using `pip install`, and it seems to be working fine.  

I haven't tried the conda build though.  Was the `pip install` working for you @rbeucher ?

**Comment by rbeucher** [comment]
yes @jmansour, no problem with ``pip install``. Not sure what is going on with the conda build. 
I am going to need a mac for that...

**Comment by rbeucher** [comment]
OK I'm merging this and starting the release work.

**Pull request merged**
