### PR TITLE
Move to PerCellSpaceFillerLayout

### PR DESCRIPTION
**Pull request by julesghub**
Switching particle based models to use PerCellSpaceFillerLayout instead of
GlobalSpaceFillerLayout.
The Global layout routine was not scalable in parallel and behaved badly
for everything other than uniform cartesian meshes.

Romain be aware for UWGeo, it should probably be updated too.

### CODE REVIEW

**Comment by jmansour** [comment]
Nice @julesghub!

This is definitely the way forward. It occurs to me that there might even be some minor performance improvements as nearby particles should be also nearby in memory so perhaps better cache usage.  Similarly for loading data from disk. 

Just reviewing the changes using github's fancy image comparison tools, and I notice that visually the per cell layout is in some instances a bit _artifacty_. I'm guessing it won't have a bearing on accuracy, but I'm wondering if some minor tweaks to the algorithm might give a better visual result.

In terms of accuracy, have any tests been run to ensure we're still getting identical results?  We discussed the analytic tests, and they don't currently use particles, but it might actually be a good regression test to have one of the analytic models using particles to obtain viscosity/density. This way we could test for differences with different layouts (and  also other particle related changes).

**Comment by rbeucher** [comment]
Yes, based on our discussions, I think it makes much more sense. I will change UWGeodynamics accordingly.

Romain

**Comment by RebeccaFarrington** [comment]
Yes, I also think this is good. 
As @jmansour mentions, we should run some tests before adopting the new layout. 
👍

**Comment by jmansour** [comment]
This has been done now.

**Pull request closed without merging**
