### PR TITLE
Update PETSc to 3.13.2

### PR DESCRIPTION
**Pull request by brmather**
Bump PETSc to 3.13.2 and separate the HDF5 1.12.0 build from petsc's configure stage.

### CODE REVIEW

**Comment by julesghub** [comment]
I like it, good to see a petsc-3.13.2 image.
Question - should this docker live in the underworld2 repo. Perhaps a `uw-dockerfiles` repo under underworldcode is more appropriate?

**Comment by jmansour** [comment]
Is UW even petsc 3.13.2 compatib?  I'm seeing compile time problems.

**Comment by jmansour** [comment]
Actually, yeah this (and possibly other Dockerfiles) should probably be pulled out and housed in their own repo.

**Comment by brmather** [comment]
Yeah maybe these should go in a separate repo. I'll leave this decision to the lords of the Underworld...

**Comment by julesghub** [comment]
Obsolete PR, we're beyond PETSc-3.13 now.

**Pull request closed without merging**
