### PR TITLE
Updates for docker image generation:

### PR DESCRIPTION
**Pull request by jmansour**
* Switch deprecated `MAINTAINER` tag for new `LABEL` construct.
* Set `/opt` to ugo+rwx to allow users to install new pip packages.
* Remove `tini` which no longer appears to be required (and wasn't
  being used previously in any case).
* Remove extras for notebook MPI usage, as this wasn't being used
  and is easy to reinstall.
* Update UW image to point to newest base file image.

### CODE REVIEW

**Comment by jmansour** [comment]
update changes!

**Comment by jmansour** [comment]
* flag removal of petsc4py too

**Comment by julesghub** [comment]
@jmansour  Make changes in the change.md

**Review by julesghub — APPROVED** [review]
Looking good

**Pull request merged**
