### PR TITLE
Adding argument 'gauss_swarm' to all fem system objects.

### PR DESCRIPTION
**Pull request by julesghub**
If provided the 'gauss_swarm' will be used for numerical
integration rather than a default gauss integration swarm that is
automatically generated and dependent on the element order of the mesh.

NB: if a voronoi_swarm is defined it OVERRIDES this gauss_swarm as the
preferred integration swarm (quadrature method).

### CODE REVIEW

**Comment by julesghub** [comment]
All test are passing and I've added an error check to see if handed `gauss_swarm` is the right object.
@jmansour please review.

**Comment by jmansour** [comment]
👍👍

I'll take a look shortly.

**Review by jmansour — APPROVED** [review]
Ok, I've added a test and a few other minor tweaks.  Good to go. Apologies for tardyness!

**Comment by julesghub** [comment]
cheers @jmansour

**Pull request merged**
